version: 2
updates:
# swift package manager is not yet supported
#- package-ecosystem: spm
#  directory: "/"
#  schedule:
#    interval: daily
#    time: "10:00"
#  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
